### ISSUE TITLE
任务类型，能否支持SQL语句

### ISSUE THREAD

**Issue by hulang** [yzh52521/http-crontab#1]
任务类型 (1 command, 2 class, 3 url 4 shell)

**Comment by yuanzhihai** [comment]
class 类型里只想sql 呗

**Comment by hulang** [comment]
@yzh52521 那不是要写很多方法，我目前很多SQL额。。
另外老大你README太简单了。。我安装到要去：https://packagist.org/ 搜索:composer require yzh52521/http-crontab
我还不会配置。。配置config/console.php文件  怎么写。。你写到：README里面啊。。你截图的那个后台管理界面，我。。。。。。。我想要。。。怎么运行。。
https://camo.githubusercontent.com/43f643a07c07f25bef20f859823076bf294e4b2ded0f5372e78a8d5d5f456088/68747470733a2f2f7777772e776f726b65726d616e2e6e65742f75706c6f61642f696d672f32303232303431322f31323632353530363336346532392e706e67

**Comment by yuanzhihai** [comment]
> 

使用 demo
https://gitee.com/yzh52521/think-crontab-demo

**Comment by hulang** [comment]
怎么配置日志不进行年月存储，config/crontab.php  能否加个配置。。。

**Comment by yuanzhihai** [comment]
> 

你是要放到一个表？

**Comment by hulang** [comment]
@yzh52521 是的，反正每隔两个月会自动清理，两月之前的数据.

**Comment by yuanzhihai** [comment]
> @yzh52521 是的，反正每隔两个月会自动清理，两月之前的数据.

升级最新
任务日志表 去除后缀了 放到一个表了

**Comment by hulang** [comment]
@yzh52521 可以了。
https://github.com/yzh52521/thinkphp-filesystem-cloud
作者老大，我FTP和SFTP，我测试，都是上传文件是本地目录。。不是上传到了FTP空间，和SFTP指定的liunx目录中。

**Comment by hulang** [comment]
@yzh52521 只有增加crontabCreate，没有全部修改吗？crontabModify函数，只能一个一个修改。不能整个修改吗？
