### ISSUE TITLE
type=2，一直提示：方法或类不存在或者错误

### ISSUE THREAD

**Issue by hulang** [yzh52521/http-crontab#2]
字段如下：
| id | title | type | rule        | target              |
|----|-------|------|-------------|---------------------|
| 1  | 访问者信息 | 2    | * * * * * * | app\query\Fun@index |

访问：http://域名/query/fun/index   没有问题，我哪里错误了？

**Comment by yuanzhihai** [comment]
是不是脚本已经运行了 
后增加的 app\query\Fun 这个类？
要重启脚本

**Comment by hulang** [comment]
@yzh52521 我win10 下调试运行的，我直接：Ctrl+C  结束了，再：php think crontab start

**Comment by hulang** [comment]
@yzh52521 app\query\Fun 这个类，很早就有了
现在定时任务越来越多了，而且我们项目是卖出去的那种，之前一直使用：URL模式
每卖出一份项目，帮客户部署项目，就得改URL里面的域名，现在想直接用：type=2 模式，直接这样，免得每次修改定时任务这块。。

**Comment by yuanzhihai** [comment]
win下 没有试过，没有环境
其他环境都正常

**Comment by hulang** [comment]
我是用Laragon 6.0.0 集成环境，PHP 7.4

**Comment by yzh52521** [comment]
自己打断点调试吧


`  if (class_exists( $class ) && method_exists( $class,$method )) {
                    try {
                        $result     = true;
                        $code       = 0;
                        $instance   = Container::getInstance()->make( $class );
                        $parameters = !empty( $data['parameter'] ) ? json_decode( $data['parameter'],true ) : [];
                        if (!empty( $parameters )) {
                            $res = $instance->{$method}( $parameters );
                        } else {
                            $res = $instance->{$method}();
                        }
                    } catch ( \Throwable $throwable ) {
                        $result = false;
                        $code   = 1;
                    }
                    $exception = isset( $throwable ) ? $throwable->getMessage() : $res;
                } else {
                    $result    = false;
                    $code      = 1;
                    $exception = "方法或类不存在或者错误";
                }`

**Comment by yuanzhihai** [comment]
断点调试吧

**Comment by yuanzhihai** [comment]
```
if (class_exists( $class ) && method_exists( $class,$method )) { 


}else {
                    $result    = false;
                    $code      = 1;
                    $exception = "方法或类不存在或者错误";
                }
```
说明没有找到类

**Comment by hulang** [comment]
@yzh52521 我使用PHP_Xdebug调试
if (class_exists($class) && method_exists($class, $method)) {
====$class提示：app\query\Fun
if (class_exists($class)

====$class提示：app\query\Fun    $method提示：index
method_exists($class, $method))

..............不知道什么问题，我要去外地了。下次回来再弄。。

**Comment by hulang** [comment]
@yzh52521 查了下class_exists($class)返回的是false，网上说是thinkphp 命名空间问题，如何解决吗？
比如我的是：app\query\Fun@index
那么命名空间是：namespace app\query\controller;

**Comment by hulang** [comment]
@yzh52521 var_dump(class_exists('\app\query\Fun'));  返回：bool(false)

**Comment by hulang** [comment]
@yzh52521 已解决，要加上：controller。。。
var_dump(class_exists('app\query\controller\Fun'));
返回：true....
