### ISSUE TITLE
调用参数parameter怎么填写啊？

### ISSUE THREAD

**Issue by hulang** [yzh52521/http-crontab#3]
调用参数 url和shell和sql任务参数无效
使用Class 任务

app\query\controller\Fun\User@list

list方法
list($id = 0, $bm_id = 0, $key = '')

我应该怎么写呢？

**Comment by yuanzhihai** [comment]
parameter 参数  数据存 {"id":1,"bm_id":2,"key":""}

list 方法参数传一个 数组

list($param)

**Comment by hulang** [comment]
@yzh52521 谢谢了。

**Comment by hulang** [comment]
@yzh52521 我很多的方法里面返回的是json数据，使用class，无法获取最后返回的json数据。。使用URL访问可以获取到。
我应该怎么做？

**Comment by yuanzhihai** [comment]
没明白啥意思

**Comment by hulang** [comment]
@yzh52521  比如我的URL
域名/query/fun/getUpdateUserCount得到结果
`{"code":1,"data":[],"uptime":"2022-10-18 09:58:51"}`
我想使用class类型获取
app\query\controller\fun@getUpdateUserCount
也想获取到结果
`{"code":1,"data":[],"uptime":"2022-10-18 09:58:51"}`
目前无法获取到。

**Comment by yuanzhihai** [comment]
可以获取到啊，

$exception = isset($throwable) ? $throwable->getMessage() : $res; 
都记录到日志里了啊

**Comment by hulang** [comment]
@yzh52521 没有获取到。日志字段exception是空的。。。

**Comment by yuanzhihai** [comment]
class 方法返回到是字符串  
return json_encode(['code'=>1,'data'=>[],'uptime'=>time()]);

**Comment by hulang** [comment]
@yzh52521 原来如此。。
