### ISSUE TITLE
测试class调用参数没有执行

### ISSUE THREAD

**Issue by hulang** [yzh52521/http-crontab#4]
比如：app\query\controller\Fun@getUpdateUserCount   参数是：{"uptime":1}
getUpdateUserCount方法
    public function getUpdateUserCount($uptime = 0)
    {
        $json = [];
        if ($uptime == 1) {
            $json['uptime'] = date('Y-m-d H:i:s', time());
        }
        $json['data'] = getUpdateUserCount();
        return json_encode($json);
    }

打开调试，进了：$parameters = json_decode($data['parameter'], true); 显示数组：uptime:1
也进入了：$res = $instance->{$method}($parameters);
返回的没有：$json['uptime'] = date('Y-m-d H:i:s', time());的参数。

**Comment by yuanzhihai** [comment]
```
public function getUpdateUserCount($param)
{
$json = [];
if ($param['uptime'] == 1) {
$json['uptime'] = date('Y-m-d H:i:s', time());
}
$json['data'] = getUpdateUserCount();
return json_encode($json);
}
```
改成这样

**Comment by hulang** [comment]
> ```
> public function getUpdateUserCount($param)
> {
> $json = [];
> if ($param['uptime'] == 1) {
> $json['uptime'] = date('Y-m-d H:i:s', time());
> }
> $json['data'] = getUpdateUserCount();
> return json_encode($json);
> }
> ```
> 
> 改成这样

可以了。。我如果用网页访问，应该怎么访问啊？param怎么输入？
域名/query/fun/getUpdateUserCount后面怎么写？

**Comment by yuanzhihai** [comment]
为什么要牵扯web访问呢？

**Comment by hulang** [comment]
@yzh52521 有时候，直接URL访问方便些，Laragon，xdebug调试起来，PHP会很卡

**Comment by yuanzhihai** [comment]
控制器怎么调用类 这个不是基础么？

**Comment by hulang** [comment]
@yzh52521 这个会啊。。
我说的是
public function getUpdateUserCount($param)
{
$json = [];
if ($param['uptime'] == 1) {
$json['uptime'] = date('Y-m-d H:i:s', time());
}
$json['data'] = getUpdateUserCount();
return json_encode($json);
}

域名/query/fun/getUpdateUserCount?param这里怎么写啊？
我只会带参数这种
域名/query/fun/getUpdateUserCount?uptime=1
数组的不会。。

**Comment by hulang** [comment]
@yzh52521 知道怎么弄了。
